# Generated by Django 3.1.4 on 2021-09-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=25, unique=True)),
                ('bot_color', models.CharField(max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.DecimalField(decimal_places=4, max_digits=30)),
                ('x', models.DecimalField(decimal_places=4, max_digits=30)),
                ('y', models.DecimalField(decimal_places=4, max_digits=30)),
                ('angle', models.DecimalField(decimal_places=4, max_digits=30)),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bots',
                'ordering': ('-id',),
            },
        ),
    ]
