# Generated by Django 3.1.4 on 2021-09-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyvyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmodel',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
