# Generated by Django 3.1.4 on 2021-09-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkyvyApp', '0002_botmodel_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botmodel',
            old_name='delivered',
            new_name='delivering',
        ),
    ]
